### ISSUE TITLE
Question for data representation(type)

### ISSUE THREAD

**Issue by TLB-MISS** [GAP-LAB-CUHK-SZ/TO-Scene#2]
I think the TO-scene presented in the paper constructed mesh representations.
In github, but dataset is constructed by point cloud.
Is there any plan to release mesh dataset?

Thanks

**Comment by bbbbubble** [comment]
Hi! We can obtain point cloud and mesh through TSDF reconstruction. However, in order to improve the reconstruction quality, we set the voxel size parameter to a relative small value, resulting in a large density of small objects' points (far more dense than Scannet furniture).
Therefore, to ensure consistency, we then apply FPS on small objects' points which lose the connectivity information. That's why we didn't provide mesh format of our dataset.

You can get the mesh format of our dataset in two ways:
(1) I will release the original CAD placement file (json file, describing the position,scale,orientation of the small objects) in two days. You can run your own rendering and reconstruction based on that file, with the point density in your control.
(2) You can directly utilize some of the typical remesh methods on our provided point cloud data.

Thank you for your interest in our dataset.

**Comment by TLB-MISS** [comment]
@bbbbubble Thanks for the quick reply!
I look forward to using your dataset soon :)

**Comment by bbbbubble** [comment]
I have release the original annotation file. You can build your own dataset (including mesh format) based on that.
https://github.com/GAP-LAB-CUHK-SZ/TO-Scene#3-build-your-own-dataset
